name: "Enterprise Cloud Landing Zone - GitOps"

on:
  # Despliegue automático (CI/CD) al hacer merge/push a la rama principal
  push:
    branches:
      - main
  
  # Gatillo manual (FinOps) para aplicar o destruir el stack a voluntad
  workflow_dispatch:
    inputs:
      action:
        description: 'Acción de Terraform a ejecutar'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

env:
  AWS_REGION: "us-east-1"
  # Las credenciales se leen de forma segura desde los secretos del repositorio
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-pipeline:
    name: "Terraform CI/CD & FinOps"
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout del Código
        uses: actions/checkout@v4
        
      - name: ⚙️ Setup de Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.0"
          
      - name: 🚀 Orquestador de Despliegue (Apply)
        if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply')
        run: |
          echo "================================================="
          echo " Iniciando Flujo GitOps (Init + Plan + Apply)"
          echo "================================================="
          chmod +x deploy.sh
          ./deploy.sh

      - name: 🔥 Orquestador de Limpieza (Destroy)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: |
          echo "================================================="
          echo " Iniciando Flujo FinOps (Destrucción Total)"
          echo "================================================="
          # El orden de destrucción OBLIGATORIAMENTE debe ser inverso al de creación
          # de lo contrario, Terraform arrojará errores de dependencias en AWS.
          MODULES=("03-observability" "02-compute" "01-network")
          
          for MODULE in "${MODULES[@]}"; do
              echo "📦 Destruyendo Módulo: $MODULE"
              cd $MODULE
              
              terraform init -input=false
              terraform destroy -auto-approve -input=false
              
              cd ..
          done
          echo "✅ ¡Destrucción Multi-Módulo Completada! (Cero costos)"
